name: RDReed
favicon: null
layout_spectrum: 0.44701
typography_spectrum: 0.8170213
title: rdreed
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefef4'
    - '#020307'
    - '#778f2f'
    - '#4f3c36'
    - '#d1c593'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
