name: RDReed
favicon: null
layout_spectrum: 0.51809
typography_spectrum: 0.49554
title: rdreed
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff7f5'
    - '#e0ddcb'
    - '#899987'
    - '#3b3a38'
    - '#62766d'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
