name: RDReed
favicon: null
layout_spectrum: 0.44701
typography_spectrum: 0.8170213
title: rdreed
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#393939'
    - '#000000'
    - '#C6C6C6'
    - '#17C51F'
  brandStrength: 0.75
  lightness: 0.806383
  saturation: 0.3446808
  rhythmicContrast: 0.7489362
purpose: []
